# Maintainer: Andrea055
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=wineget-bin
pkgver=1.0.0
pkgrel=1
pkgdesc="Wineget(WNG) is a package manager for Wine written with Rust"
url="https://github.com/Windows-On-Linux/"
license=("LICENSE")
arch=("x86_64")
provides=("wineget")
conflicts=("wineget")

source=("https://github.com/Windows-On-Linux/Wineget/releases/download/v$pkgver/wineget-$pkgver-x86_64.tar.gz")
sha256sums=("a39b0bcf643ab5d2d79b08ae89056f1682664c5339815298b149d7923d707993")

package() {
    install -Dm755 wineget -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
