# Maintainer: Andrea055
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=wineget-bin
pkgver=1.2.0
pkgrel=1
pkgdesc="Wineget(WNG) is a package manager for Wine written with Rust"
url="https://github.com/Windows-On-Linux/"
license=("LICENSE")
arch=("x86_64")
provides=("wineget")
conflicts=("wineget")

source=("https://github.com/Windows-On-Linux/Wineget/releases/download/$pkgver/wineget-$pkgver-x86_64.tar.gz")
sha256sums=("dfa36149238d9e50ce90d847a060f27ad8fba9fc74a09ad2ba42b5d8114fe2eb")

package() {
    install -Dm755 wineget -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
